### PR TITLE
WIP: Update to 4.3.0 and update pinning

### PR DESCRIPTION
**Pull request by kmuehlbauer**
successor of #7 and #8

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf

I had to create this new pr, because we need to add something to build.sh also. I have the cmake build tested (see comments), this doesn't work yet, because [ncxx4-config isn't generated](https://github.com/Unidata/netcdf-cxx4/issues/36). So I had to put in the whole stuff for automake and friends.

**Comment by pelson** [comment]
Looks sensible to me. 👍

**Comment by kmuehlbauer** [comment]
Strange behaviour here experiencing. If using `autoreconf` it complains about missing `perl`.

**Comment by kmuehlbauer** [comment]
OK, we'll use the precompiled `configure` until the `autoreconf` stuff is sorted out. See also https://circleci.com/gh/conda-forge/xraylib-feedstock/1 which fails with the same error. @ericdill any thoughts?

**Comment by kmuehlbauer** [comment]
@ocefpaf @pelson

I'm not sure, what's going on with the travis builds. 

`checking build system type... i386-apple-darwin13.4.0` 

is detected instead of 

`checking build system type... x86_64-apple-darwin13.4.0`

Finally failing with:
```bash
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/Users/travis/miniconda3/conda-bld/work/netcdf-cxx4-4.3.0':
configure: error: C compiler cannot create executables
```

Unfortunately config.log can't be displayed after failing.

**Comment by kmuehlbauer** [comment]
I've hacked .travis.yml to get config.log displayed.

**Comment by ocefpaf** [comment]
> Strange behaviour here experiencing. If using `autoreconf` it complains about missing `perl`.

I've seen that before. No idea what is going on :unamused:

**Comment by ocefpaf** [comment]
I am guessing the new docker image might be lacking `perl`. So we need to rebuild `autoreconf` and add `perl` as a dependency there. (This might fix a lot of failures I am seeing.)

Pinging @pelson who might sniff if we are in a red-herring search or if this sounds reasonable.

**Comment by kmuehlbauer** [comment]
Here is evidence, I put a `which perl` in the build-script:

https://circleci.com/gh/conda-forge/netcdf-cxx4-feedstock/25
```
+ which perl
which: no perl in (/opt/conda/envs/_build/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
Command failed: /bin/bash -x -e /recipe_root/build.sh
```

**Comment by pelson** [comment]
Sounds plausible if autoreconf needs perl. I'm afraid I don't have the cycles today to look at this though. Are you happy to take a look at fixing?

**Comment by ocefpaf** [comment]
> Sounds plausible if autoreconf needs perl. I'm afraid I don't have the cycles today to look at this though. Are you happy to take a look at fixing?

Already on it https://github.com/conda-forge/autoconf-feedstock/pull/8

(Save your cycles for  better things. I am happy to do this while I watch 6 hours straight of presentations about Data Management :wink:)

**Comment by kmuehlbauer** [comment]
For the travis-failures:

https://travis-ci.org/conda-forge/netcdf-cxx4-feedstock/builds/134728607#L599

```
configure:3684: checking for gcc
configure:3711: result: clang
configure:3940: checking for C compiler version
configure:3949: clang --version >&5
sh: line 1:   927 Trace/BPT trap: 5       /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find clang 2> /dev/null
clang: error: unable to find utility "clang", not a developer tool or in PATH
```

**Comment by kmuehlbauer** [comment]
OK, here is what I have:

1. `configure` - based build breaks on osx for an unknown reason
2. `cmake` - based build works, but misses ncxx4-config (see https://github.com/Unidata/netcdf-cxx4/issues/36)

I'll stop iterating here.

We could hack something together to get `ncxx4-config` working, but it would be better to have it right from the sources. ping @WardF

**Comment by WardF** [comment]
I'm at a workshop today and tomorrow but I'll address the `ncxx4-config` issue that's been opened.  I wonder if the problem with `configure` on OSX is related to the issue discussed here: https://github.com/conda-forge/staged-recipes/pull/213#issuecomment-220734923

**Comment by kmuehlbauer** [comment]
@WardF Thanks for your quick response, it is very welcome. Thanks for the osx-pointer, I'll have a look into this.

**Comment by kmuehlbauer** [comment]
I'll clean up everything, when the cmake-ncxx4 issue is sorted out, also if this means to wait some time.

I have the hardest time to get autoconf/automake running properly, so switching to the working cmake is probably best.

**Comment by ocefpaf** [comment]
> I have the hardest time to get autoconf/automake running properly, so switching to the working cmake is probably best. 

:+1: (Although I am trying `cmake` with netcdf-fortran and failing right :grin:)

**Comment by jakirkham** [comment]
So what was the issue with `autoconf`(?) and `perl`?

**Comment by jakirkham** [comment]
NVM I see it. Makes sense. Good detective work @kmuehlbauer. :shipit: (I know it was the closest thing I could find 😉)

**Comment by kmuehlbauer** [comment]
I have PR https://github.com/Unidata/netcdf-cxx4/pull/37 ready, which fixes the `ncxx4-config`-issue  with the cmake builds. Hopefully the guys at unidata find some time to get this in.

**Comment by kmuehlbauer** [comment]
Since at unidata everything is green in their build, I have added this as a patch here to move forward.

**Comment by ocefpaf** [comment]
> Since at unidata everything is green in their build, I have added this as a patch here to move forward.

Agreed. That is a fine strategy to backport things. (I am still stuck with `netcdf-fortran`, but I will try again tomorrow.)

**Comment by WardF** [comment]
I'll review the pull request today and get it merged unless something unusual occurs!

**Comment by kmuehlbauer** [comment]
@WardF It seems, that there is some glitch within the build ncxx4-config left, which I could not figure out yet.

**Comment by WardF** [comment]
No problem; I really appreciate the pull request as it's a great starting place.  I've got some other stuff on my plate (https://github.com/Unidata/netcdf-c/issues/239) but will turn my attention to this as soon as possible, I don't think it will take much to get it the rest of the way.  Thanks again!

**Comment by ocefpaf** [comment]
@kmuehlbauer should we merge this?

**Comment by kmuehlbauer** [comment]
@ocefpaf The `ncxx4-config` is broken or is reporting wrong setup.

But it should work, I'm :+1: for merge.

**Comment by kmuehlbauer** [comment]
@ocefpaf Sounds very reasonable, and yes if you could overtake :+1:

**Comment by ocefpaf** [comment]
Something changed (maybe in the docker image?) and now the Linux builds are broken :unamused:

**Comment by ocefpaf** [comment]
> Something changed (maybe in the docker image?) and now the Linux builds are broken :unamused: 

It seems to be the `toolchain` :unamused: 
See dropping it )https://github.com/conda-forge/netcdf-cxx4-feedstock/pull/10/commits/9d261e95f2ed59880bddc4b50456e6ddc740713d) solved the issue in #10

**Comment by kmuehlbauer** [comment]
@ocefpaf 

The ncxx4-issue is solved at unidata (https://github.com/Unidata/netcdf-cxx4/pull/37). How do we proceed. Bump build number?

**Comment by ocefpaf** [comment]
> The ncxx4-issue is solved at unidata (https://github.com/Unidata/netcdf-cxx4/pull/37). How do we proceed. Bump build number?

The changes are not in a release, right? If so we need to backport the fix via a patch and bump the build number. But if release 4.3.1 is near we can just upadte to that once it is out.

**Pull request merged**
