### PR TITLE
Add MPI build matrix

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Add xylar as maintainer

### CODE REVIEW

**Comment by xylar** [comment]
Yay! I'm getting pretty good at this.  @ocefpaf or @kmuehlbauer, could you review this when you get a chance and merge if you're happy?

**Comment by kmuehlbauer** [comment]
@xylar Checklist is OK. Trusting your MPI knowledge. Welcome on board.

**Comment by xylar** [comment]
Sorry, looking at the build output, it doesn't look like parallel was actually detected properly.  I'm looking into it and I'll do another PR as soon as I figure out why.

**Comment by xylar** [comment]
```
-- Looking for nc_use_parallel_enabled in netcdf
-- Looking for nc_use_parallel_enabled in netcdf - not found
```

**Pull request merged**
