### PR TITLE
migrate HDF5 1.14.3 + libnetcdf 4.9.2

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

Would like to see if a simple rerender can build.  I have a suspicion that a `zlib` requirement is needed.

### CODE REVIEW

**Comment by akrherz** [comment]
simple rerender build was green, gonna try to apply the libnetcdf 4.9.1 migration along with HDF5 1.14.0 and see what happens.

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
That seemed to have helped, now we are add a test failue
> 10/18 Test #10: cxx4_test_filter .................***Failed

**Comment by akrherz** [comment]
I didn't get a response on Unidata/netcdf-cxx4#132, so am unsure if we should just skip the test or ?

**Comment by xylar** [comment]
For what it's worth, the only children seem to be `pytrilinos`, `trilinos`.

**Comment by xylar** [comment]
At least in the hdf5 migration.  If Trilinos folks want to get involved, that would be fine.  If not, that's fine, too, and we can let the is be until we hear from NCAR/UCAR.

**Comment by akrherz** [comment]
Whoa @xylar , look at what happened here!  appears the latest libnetcdf and latest hdf5 make this happy.

**Comment by xylar** [comment]
Okay, great!  Let's merge!

**Comment by akrherz** [comment]
Thanks @xylar , I have no such powers with this repo :)

**Comment by xylar** [comment]
Ah, of course!

**Pull request merged**
